name: validators
version: 2.1.0
authors:
- Luis Vargas <luisvargastijerino@gmail.com>
- Karan Goel <karan@goel.io>
description: String validation and sanitization for Dart.
homepage: https://github.com/dart-league/validators
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  vin_decoder: ^0.2.0-nullsafety # ^0.1.3
dev_dependencies:
  test: ^1.16.5
