name: validators
version: 3.0.0
authors:
- Luis Vargas <luisvargastijerino@gmail.com>
- Karan Goel <karan@goel.io>
- Brett Sutton <bsutton@noojee.com.au>
homepage: https://github.com/dart-league/validators
description: String validation and sanitization for Dart.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  vin_decoder: ^0.2.0-0
dev_dependencies: 
  test: ^1.16.5
